import PyTools
tools = PyTools.tools()
tools.console.print('Welcome to PyTools!')
tools.console.wue('Press enter for a few examples ')
tools.console.clear()
tools.console.print('Normal')
tools.console.comment('Comment')
tools.console.warn('Warn')
tools.console.print('Newline')
tools.console.newline()
tools.console.pcw('PCW')
tools.console.newline()
tools.console.wue('Press enter to continue ')
tools.console.clear()
tools.console.print("chop('test'):")
tools.console.print(tools.string.chop('test'))
tools.console.newline()
tools.console.print("listToString(['T','e','s','t']):")
tools.console.print(tools.string.listToString(['T','e','s','t']))
tools.console.newline()
tools.console.print('We also have file tools, but we think you can figure out how to use it without us.')
tools.console.print('If you want to know how to install this module, take a look at README.md if you haven\'t already')
